### ISSUE TITLE
dependencies failing on bare-bone

### ISSUE THREAD

**Issue by ishmum123** [rogeriochaves/elm-test-bdd-style#10]
Simply installing elm-test@beta and this package together produces -> 
The dependencies in your elm.json are not compatible.

**Comment by rogeriochaves** [comment]
You are right, to fix that instead of installing it as a regular elm dependency you should install with:

```
elm-test install rogeriochaves/elm-test-bdd-style
```

Then it shouldn't have any conflicts

I'll update the docs accordingly, thanks!
