### ISSUE TITLE
Order of arguments

### ISSUE THREAD

**Issue by genthaler** [rogeriochaves/elm-test-bdd-style#5]
Hi Rogerio, 

Given the usage of this library is meant to reflect idiomatic English usage, I'd expect the expression:

```
describe "Example Text"
    [ it "does not miscalculate things"
        <| expect (2 + 2) toBe 5
    ]
```

to generate the error 

```
Test Suite: Example Text: FAILED
  does not miscalculate things: FAILED. Expected: 5; got: 4
```

but it generates 

```
Test Suite: Example Text: FAILED
  does not miscalculate things: FAILED. Expected: 4; got: 5
```

**Comment by rogeriochaves** [comment]
Hello @genthaler,

Sorry for the loooong delay in replying this, I'll close as it doesn't happen anymore, much has changed since :)

Currently it breaks like this:
```
↓ Example
↓ Example Test
✗ does math correctly

    4
    ╷
    │ Expect.equal
    ╵
    5
```

**Comment by genthaler** [comment]
Yep, that seems fine :) Thanks @rogeriochaves
