### ISSUE TITLE
Work with Elm v19

### ISSUE THREAD

**Issue by dschinkel** [rogeriochaves/elm-test-bdd-style#9]
Any plans to get this working over **elm v19**?  Right now it doesn't seem to work, I can't install it via the `elm package` command anymore since there is no `package` command anymore in **v19** . If I try just `elm install`, it bombs and says that `elm-test-bdd-style` is not compatible yet

**Comment by rogeriochaves** [comment]
Done, updated to 0.19
```
elm install rogeriochaves/elm-test-bdd-style
```
should work
